fiz

diff --git a/.github/workflows/haskell-release.yml b/.github/workflows/haskell-release.yml
--- a/.github/workflows/haskell-release.yml
+++ b/.github/workflows/haskell-release.yml
@@ -48,7 +48,7 @@ jobs:
             ${{ runner.os }}-${{ matrix.ghc }}-
 
       - name: Zip data directory
-        run: zip -r swarm-data.zip ./data || { echo "Unable to create a zip archive."; exit 1;  }
+        run: zip -r artifacts/swarm-data.zip ./data || { echo "Unable to create a zip archive."; exit 1;  }
 
       - name: Set binary path name
         run: echo BINARY_PATH="./dist/swarm" >> "$GITHUB_ENV"
@@ -109,11 +109,12 @@ jobs:
             name: swarm-Darwin-arm64
             path: artifacts/swarm-Darwin-arm64
 
-        - name: Rename executables
+        - name: Rename executables and data
           run: |
               mv artifacts/swarm-Linux-x86_64/swarm  swarm-Linux-x86_64
               mv artifacts/swarm-Darwin-x86_64/swarm swarm-Darwin-x86_64
               mv artifacts/swarm-Darwin-arm64/swarm swarm-Darwin-arm64
+              mv artifacts/swarm-data.zip swarm-data.zip
 
         - name: Upload Release Asset
           uses: softprops/action-gh-release@v1
